config/routes.rb
Rails.application.routes.draw do
  resources :articles

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

	default_scope -> {order(created_at: :desc)}
	
	validates :title, presence: true,
                    length: { minimum: 3 ,maximum: 50}

    validates :text, presence: true,
    		   length: {minimum: 10 ,maximum: 250}             

    custom_slugs_with(:title)
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def redirect_to_good_slug(object)
      redirect_to params.merge({
                    :controller => controller_name,
                    :action => params[:action],
                    :id => object.to_param,
                    :status => :moved_permanently
                  })
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		
	end


	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(params.require(:article).permit(:title, :text))
  		
  		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end
	
	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title,:text)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title='')
		base_title = "Blog de Teste"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end

end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "Erros") %>
        impediram esse artigo de ser salvo:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :titulo %><br>
    <%= f.text_field :title ,onkeyup:"countChar(this.value,50,'article_title','counter_title')",onblur:"confirmValues('article_title','message_title')"  %> 
   
  </p>
  <h6 id="message_title">*Por favor, preencha o campo </h6>
   <h6 id="counter_title"> Você possui 50 caracteres restando </h6>
 
  <p>
    <%= f.label :mensagem %><br>
    <%= f.text_area :text ,onkeyup:"countChar(this.value,255,'article_text','counter_text')", onblur:"confirmValues('article_text','message_text')"%> 
  </p>
  <h6 id="message_text">*Por favor, preencha o campo </h6>
  <h6 id="counter_text"> Você possui 255 caracteres restando </h6>
  
  <p>
    <%= f.submit :Salvar, class:'btn save' %> 
    <%= link_to 'Voltar', articles_path %>
  </p>
  
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "Editar Artigos") %>
<h1>Editar Artigo</h1>

 <%= render 'form' %>

app/views/articles/index.html.erb
<% provide(:title, "Home") %>
<header>
  <%= link_to 'Novo Artigo', new_article_path, class:'btn'%> 
  <h1>Lista de Artigos</h1>
  
</header>
<article id="message">
  
  <% @articles.each do |article| %>
    <h2> 
      <%= article.title %> 
    </h2>
    <aside class="sidebar">
      <ul>
        <li> 
          <%= link_to 'Detalhes', article_path(article), class:'detail' %> </li>
        <li> 
          <%= link_to "Editar", edit_article_path(article), class:'edit' %> </li>
        <li> 
          <%= link_to 'Deletar', article_path(article),
                  method: :delete,
                  data: { confirm: 'Você tem certeza?' }, class:'delete' %>
        </li>
      </ul>
    </aside>
    <p class="article"> 
      <%= article.text %> 
    </p>
    <div id="clear">
    </div>
  <% end %>
</article>

 

app/views/articles/new.html.erb
<% provide(:title, "Escrever Novo Artigo") %>
<h1>Novo Artigo</h1>
 
 
<%= render 'form' %>
 


app/views/articles/show.html.erb
<% provide(:title, "Exibir Detalhes do Artigo") %>
<div class="details">
	<h2>
  		<strong>Titulo:</strong>
  		<%= @article.title %>
	</h2>
 
	<p class='show'>
	  <strong>Mensagem:</strong>
	  <%= @article.text %>
	</p>


	<%= link_to 'Voltar', articles_path, class:'cancel' %> |
	<%= link_to 'Editar Artigo', edit_article_path(@article), class:'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,700' rel='stylesheet' type='text/css'>
</head>
<body>
<div id="container">

		<%= yield %>
</div>
</body>
</html>